---
- hosts: kudjango
  sudo: yes
  tasks:
    - name: copy sources to kujango vm
      copy: src=../../../python dest=/app
    - name: configure Database
      template: src=templates/settings.j2 dest=/app/python/kudjango/settings.py force=yes
    - name: install requirements
      action: shell cd /app/python && pip install -r requirements.txt
    - name: start the Apply
      sudo: yes
      action: shell cd /app/python && sh run.sh
