# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.define "db00" do |db00|
    db00.vm.hostname = "db00"
    db00.vm.box = "ubuntu1404-db"
    db00.vm.network "private_network", ip: "10.11.12.103"
  end

  config.vm.define "kujango00" do |kudjango00|
    kudjango00.vm.hostname = "kudjango00"
    kudjango00.vm.box = "ubuntu1404-kudjango"
    kudjango00.vm.network "private_network", ip: "10.11.12.101"
    kudjango00.vm.network :forwarded_port, guest: 8000, host: 8000

  end

  config.vm.define "kujango01" do |kudjango01|
    kudjango01.vm.hostname = "kudjango01"
    kudjango01.vm.box = "ubuntu1404-kudjango"
    kudjango01.vm.network "private_network", ip: "10.11.12.102"
    kudjango01.vm.network :forwarded_port, guest: 8000, host: 8001

  end



  config.vm.define "front" do |front|
    front.vm.hostname = "front"
    front.vm.box = "ubuntu1404-front"
    front.vm.network :forwarded_port, guest: 9000, host: 9000
    front.vm.network :forwarded_port, guest: 80, host: 80
    front.vm.network "private_network", ip: "10.11.12.100"
  end


  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "provisioning/site.yml"
    ansible.groups = {
      "web" => ["front"],
      "kudjango" => ["kujango00", "kujango01"],
      "dbs" => ["db00"],
      "all_groups:children" => ["front", "kudjango", "dbs"],
    }
  end
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
